# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"


In [2]:
x=s.split()
for i in x:
  print(i)

Hi
there
Sam!


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of {} is {} kilometers." .format( planet , diameter ) )

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
print( d['k1'][3][ "tricky" ][3]['target'][3] )

hello


# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
a1=np.zeros(10)

In [9]:
a2=np.ones(10)*5
print(a1 , a2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
p = (np.arange(20,35,2))
print(p)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
p = np.arange(0,9).reshape((3,3))
print(p)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
a=np.array( [1,2,3])
b=np.array( [4,5,6])
l = np.concatenate( ( a , b ) )
print(l)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd


In [14]:
l = [["Anand",95], ["Bala", 85], ['Cathie', 74]]
d = pd.DataFrame( l , columns=['Name', 'score'])
print(d)

     Name  score
0   Anand     95
1    Bala     85
2  Cathie     74


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [15]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [16]:
d = pd.DataFrame( lists , columns=['SI', 'Name' , 'Marks'])
print(d)

   SI Name  Marks
0   1  aaa     22
1   2  bbb     25
2   3  ccc     24
